export const sampleRecords = [
  {
    id: 'Q-1048',
    customer: 'Olivia Carter',
    phone: '+1 555 014 8821',
    product: 'Artisan Sourdough Loaf',
    quantity: '2 loaves',
    assortment: 'Country sourdough',
    deliveryDate: 'Oct 18, 2026',
    deliveryType: 'Home delivery',
    price: '$18.00',
    status: 'Pending',
    tone: 'amber',
    details: [
      ['Product', 'Artisan Sourdough Loaf'],
      ['Quantity', '2 loaves'],
      ['Selection', 'Country sourdough'],
      ['Packaging', 'Kraft paper bags'],
      ['Delivery window', 'Before 9:00 AM'],
      ['Estimated price', '$18.00'],
    ],
    delivery: 'Home delivery · 48 Garden Lane',
    notes: 'Leave the order at the front desk if nobody answers the door.',
  },
  {
    id: 'Q-1047',
    customer: 'Noah Bennett',
    phone: '+1 555 018 2740',
    product: 'Morning Pastry Box',
    quantity: '12 pieces',
    assortment: 'Croissants and danishes',
    deliveryDate: 'Oct 21, 2026',
    deliveryType: 'Pickup',
    price: '$34.00',
    status: 'In Review',
    tone: 'blue',
    details: [
      ['Product', 'Morning Pastry Box'],
      ['Quantity', '12 pieces'],
      ['Selection', 'Croissants and danishes'],
      ['Packaging', 'Reusable bakery box'],
      ['Pickup window', '8:00–10:00 AM'],
      ['Estimated price', '$34.00'],
    ],
    delivery: 'Pickup · Bakery counter',
    notes: 'Pack the pastries separately from the coffee service supplies.',
  },
  {
    id: 'Q-1046',
    customer: 'Mia Brooks',
    phone: '+1 555 012 9456',
    product: 'Cinnamon Roll Bundle',
    quantity: '8 rolls',
    assortment: 'Classic cinnamon glaze',
    deliveryDate: 'Oct 25, 2026',
    deliveryType: 'Home delivery',
    price: '$26.00',
    status: 'Confirmed',
    tone: 'emerald',
    details: [
      ['Product', 'Cinnamon Roll Bundle'],
      ['Quantity', '8 rolls'],
      ['Selection', 'Classic cinnamon glaze'],
      ['Packaging', 'Warm insulated box'],
      ['Delivery window', '10:00–11:00 AM'],
      ['Final price', '$26.00'],
    ],
    delivery: 'Home delivery · 16 Park Avenue',
    notes: 'Deliver while the rolls are still warm and keep the box upright.',
  },
  {
    id: 'Q-1045',
    customer: 'James Rivera',
    phone: '+1 555 010 6318',
    product: 'Wholegrain Bread Basket',
    quantity: '4 loaves',
    assortment: 'Seeded wholegrain',
    deliveryDate: 'Oct 28, 2026',
    deliveryType: 'Pickup',
    price: '$29.00',
    status: 'Finalized',
    tone: 'slate',
    details: [
      ['Product', 'Wholegrain Bread Basket'],
      ['Quantity', '4 loaves'],
      ['Selection', 'Seeded wholegrain'],
      ['Packaging', 'Narrow kraft box'],
      ['Pickup window', '4:00–6:00 PM'],
      ['Final price', '$29.00'],
    ],
    delivery: 'Pickup · Bakery counter',
    notes: 'Place the care card on top of the bread before pickup.',
  },
  {
    id: 'Q-1044',
    customer: 'Ava Thompson',
    phone: '+1 555 017 5083',
    product: 'Seasonal Bread Basket',
    quantity: '6 items',
    assortment: 'Rotating bakery selection',
    deliveryDate: 'Nov 02, 2026',
    deliveryType: 'Home delivery',
    price: '$46.00',
    status: 'Cancelled',
    tone: 'rose',
    details: [
      ['Product', 'Seasonal Bread Basket'],
      ['Quantity', '6 items'],
      ['Selection', 'Rotating bakery selection'],
      ['Packaging', 'Woven market basket'],
      ['Delivery window', 'Afternoon route'],
      ['Estimated price', '$46.00'],
    ],
    delivery: 'Home delivery · 27 Willow Street',
    notes: 'Cancelled by the customer before the morning baking shift.',
  },
  {
    id: 'Q-1043',
    customer: 'Ethan Morgan',
    phone: '+1 555 019 1124',
    product: 'Breakfast Delivery Box',
    quantity: '20 items',
    assortment: 'Breads, pastries, and spreads',
    deliveryDate: 'Nov 07, 2026',
    deliveryType: 'Home delivery',
    price: '$72.00',
    status: 'Pending',
    tone: 'amber',
    details: [
      ['Product', 'Breakfast Delivery Box'],
      ['Quantity', '20 items'],
      ['Selection', 'Breads, pastries, and spreads'],
      ['Packaging', 'Recyclable catering boxes'],
      ['Delivery window', 'Before 8:00 AM'],
      ['Estimated price', '$72.00'],
    ],
    delivery: 'Home delivery · 9 Harbor Road',
    notes: 'Please confirm the delivery entrance with the customer the day before.',
  },
];

export function toDetailRecord(record) {
  return {
    id: record.id,
    title: record.customer,
    subtitle: `${record.product} · ${record.phone}`,
    status: record.status,
    tone: record.tone,
    fields: record.details,
    sections: [
      { icon: 'location', label: 'Delivery', value: record.delivery },
      { icon: 'calendar', label: 'Delivery date', value: record.deliveryDate },
      { icon: 'note', label: 'Notes', value: record.notes, multiline: true },
    ],
  };
}
