export const sampleRecords = [
  {
    id: 'Q-1048',
    customer: 'Olivia Carter',
    phone: '+1 555 014 8821',
    product: 'Chocolate Celebration Cake',
    servings: '24 servings',
    filling: 'Salted caramel',
    deliveryDate: 'Oct 18, 2026',
    deliveryType: 'Home delivery',
    price: '$86.00',
    status: 'Pending',
    tone: 'amber',
    details: [
      ['Product', 'Chocolate Celebration Cake'],
      ['Servings', '24 servings'],
      ['Filling', 'Salted caramel'],
      ['Coverage', 'Dark chocolate ganache'],
      ['Personalization', 'Olivia · 30 years'],
      ['Estimated price', '$86.00'],
    ],
    delivery: 'Home delivery · 48 Garden Lane',
    notes: 'Keep the color palette warm and add a small gold topper.',
  },
  {
    id: 'Q-1047',
    customer: 'Noah Bennett',
    phone: '+1 555 018 2740',
    product: 'Vanilla Garden Cake',
    servings: '16 servings',
    filling: 'Strawberry cream',
    deliveryDate: 'Oct 21, 2026',
    deliveryType: 'Pickup',
    price: '$62.00',
    status: 'In Review',
    tone: 'blue',
    details: [
      ['Product', 'Vanilla Garden Cake'],
      ['Servings', '16 servings'],
      ['Filling', 'Strawberry cream'],
      ['Coverage', 'Vanilla buttercream'],
      ['Personalization', 'Pressed flower finish'],
      ['Estimated price', '$62.00'],
    ],
    delivery: 'Pickup · Workshop counter',
    notes: 'Customer will bring the topper. Keep the top surface flat.',
  },
  {
    id: 'Q-1046',
    customer: 'Mia Brooks',
    phone: '+1 555 012 9456',
    product: 'Red Velvet Number Cake',
    servings: '30 servings',
    filling: 'Cream cheese',
    deliveryDate: 'Oct 25, 2026',
    deliveryType: 'Home delivery',
    price: '$108.00',
    status: 'Confirmed',
    tone: 'emerald',
    details: [
      ['Product', 'Red Velvet Number Cake'],
      ['Servings', '30 servings'],
      ['Filling', 'Cream cheese'],
      ['Coverage', 'Berry and cream finish'],
      ['Personalization', 'Number 25'],
      ['Final price', '$108.00'],
    ],
    delivery: 'Home delivery · 16 Park Avenue',
    notes: 'Use fresh berries and keep the number clearly visible.',
  },
  {
    id: 'Q-1045',
    customer: 'James Rivera',
    phone: '+1 555 010 6318',
    product: 'Lemon Drizzle Loaf',
    servings: '12 servings',
    filling: 'Lemon curd',
    deliveryDate: 'Oct 28, 2026',
    deliveryType: 'Pickup',
    price: '$44.00',
    status: 'Finalized',
    tone: 'slate',
    details: [
      ['Product', 'Lemon Drizzle Loaf'],
      ['Servings', '12 servings'],
      ['Filling', 'Lemon curd'],
      ['Coverage', 'Citrus glaze'],
      ['Personalization', 'Minimal finish'],
      ['Final price', '$44.00'],
    ],
    delivery: 'Pickup · Workshop counter',
    notes: 'Pack in the narrow kraft box with the care card on top.',
  },
  {
    id: 'Q-1044',
    customer: 'Ava Thompson',
    phone: '+1 555 017 5083',
    product: 'Pistachio Birthday Cake',
    servings: '20 servings',
    filling: 'Pistachio mousse',
    deliveryDate: 'Nov 02, 2026',
    deliveryType: 'Home delivery',
    price: '$92.00',
    status: 'Cancelled',
    tone: 'rose',
    details: [
      ['Product', 'Pistachio Birthday Cake'],
      ['Servings', '20 servings'],
      ['Filling', 'Pistachio mousse'],
      ['Coverage', 'White chocolate shell'],
      ['Personalization', 'Green ribbon finish'],
      ['Estimated price', '$92.00'],
    ],
    delivery: 'Home delivery · 27 Willow Street',
    notes: 'Cancelled by the customer before production started.',
  },
  {
    id: 'Q-1043',
    customer: 'Ethan Morgan',
    phone: '+1 555 019 1124',
    product: 'Caramel Dessert Table',
    servings: '40 servings',
    filling: 'Vanilla cream',
    deliveryDate: 'Nov 07, 2026',
    deliveryType: 'Home delivery',
    price: '$138.00',
    status: 'Pending',
    tone: 'amber',
    details: [
      ['Product', 'Caramel Dessert Table'],
      ['Servings', '40 servings'],
      ['Filling', 'Vanilla cream'],
      ['Coverage', 'Caramel glaze'],
      ['Personalization', 'Custom dessert labels'],
      ['Estimated price', '$138.00'],
    ],
    delivery: 'Home delivery · 9 Harbor Road',
    notes: 'Please confirm the table layout before the final quote.',
  },
];

export function toDetailRecord(record) {
  return {
    id: record.id,
    title: record.customer,
    subtitle: `${record.product} · ${record.phone}`,
    status: record.status,
    tone: record.tone,
    fields: record.details,
    sections: [
      { icon: 'location', label: 'Delivery', value: record.delivery },
      { icon: 'calendar', label: 'Delivery date', value: record.deliveryDate },
      { icon: 'note', label: 'Notes', value: record.notes, multiline: true },
    ],
  };
}
